sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '4.0'
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - npm install
  - gulp script
